sudo: false
language: node_js
node_js:
  - '6'
  - '8'
cache:
  directories:
    - node_modules
    - packages/*/node_modules
before_script:
  - npm run setup
after_script:
  - npm run cover
  - npm run cover:upload
matrix:
  fast_finish: true
