sudo: false
language: node_js
node_js:
  - '6'
cache:
  yarn: true
  directories:
    - node_modules
    - packages/*/node_modules
before_script:
  - yarn run setup
after_script:
  - yarn run cover
matrix:
  fast_finish: true
